services:
  gateway:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9091:9091"
    environment:
      GATEWAY_REDIS_URL: "redis://redis:6379"
    volumes:
      - ../config.yaml:/config.yaml:ro
    command: ["-config", "/config.yaml"]
    depends_on:
      redis:
        condition: service_healthy
      orders:
        condition: service_started
      users:
        condition: service_started

  orders:
    image: hashicorp/http-echo:1.0
    command: ["-listen=:8081", "-text=orders ok"]

  users:
    image: hashicorp/http-echo:1.0
    command: ["-listen=:8082", "-text=users ok"]

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  prometheus:
    image: prom/prometheus:v2.53.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
